### ISSUE TITLE
Python SDK Api - listing resources

### ISSUE THREAD

**Issue by flipmcf** [nuclia/support#8]
https://docs.nuclia.dev/docs/api#tag/Search/operation/List_resources_of_a_Knowledge_Box_kb__kbid__catalog_get

documentation says query defaults to an empty string, but it's actually required:

```
>>> query = sdk.NucliaSearch()
>>> results = query.search(url=uri,
... api_key=API_KEY)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "./venv/lib/python3.9/site-packages/nuclia/decorators.py", line 75, in wrapper_checkout_kb
    return func(*args, **kwargs)
  File "./venv/lib/python3.9/site-packages/nuclia/decorators.py", line 116, in wrapper
    result = func(*args, **kwargs)
TypeError: search() missing 1 required keyword-only argument: 'query'
```

**Comment by ebrehault** [comment]
Fixed by https://github.com/nuclia/nuclia.py/pull/19/commits/8a233f223d286cf0f371aa48258302cf3f0b1d35
